from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


@dataclass(frozen=True)
class QuestionBlueprint:
    topic: str
    question: str
    correct_answer: str
    distractors: Sequence[str]
    rule: str
    explanation: str
    sentence_explanation: str
    secondary_topics: Sequence[str] = ()


QUESTION_BANK: list[QuestionBlueprint] = [
    QuestionBlueprint(
        topic="Choosing the correct word to complete a simple sentence",
        question="They ___ ready for the meeting.",
        correct_answer="are",
        distractors=("is", "was", "be", "been"),
        rule="Use the plural form of the verb when the subject is plural.",
        explanation="They is a plural subject, so the sentence needs the plural verb are.",
        sentence_explanation="They are ready for the meeting.",
    ),
    QuestionBlueprint(
        topic="Personal pronouns",
        question="Between you and ___, the plan changed.",
        correct_answer="me",
        distractors=("I", "she", "they", "we"),
        rule="Use an object pronoun after a preposition.",
        explanation="Between is a preposition, so the pronoun after it should be me.",
        sentence_explanation="Between you and me, the plan changed.",
    ),
    QuestionBlueprint(
        topic="Subject-verb agreement",
        question="The list of items ___ on the table.",
        correct_answer="is",
        distractors=("are", "were", "be", "have been"),
        rule="The main subject is list, which is singular.",
        explanation="The subject list is singular, so the verb must be is.",
        sentence_explanation="The list of items is on the table.",
    ),
    QuestionBlueprint(
        topic="Adverb phrases",
        question="She spoke ___ during the interview.",
        correct_answer="clearly",
        distractors=("clear", "quick", "bright", "softness"),
        rule="An adverb phrase or adverb form modifies the verb spoke.",
        explanation="Clearly is the adverb that describes how she spoke.",
        sentence_explanation="She spoke clearly during the interview.",
    ),
    QuestionBlueprint(
        topic="Appositives",
        question="My brother, ___, will drive us home.",
        correct_answer="a skilled mechanic",
        distractors=("skillfully", "many cars", "to fix the car", "who fixes"),
        rule="An appositive renames the noun that comes before it.",
        explanation="A skilled mechanic is a noun phrase that renames my brother.",
        sentence_explanation="My brother, a skilled mechanic, will drive us home.",
    ),
    QuestionBlueprint(
        topic="Noun phrases",
        question="The decision ___ surprised everyone.",
        correct_answer="to postpone the launch",
        distractors=("postponing launch", "postpone launch", "postponed launch", "postpone to the launch"),
        rule="A noun phrase can function as the subject or object of a sentence.",
        explanation="To postpone the launch is a noun phrase that completes the subject decision.",
        sentence_explanation="The decision to postpone the launch surprised everyone.",
    ),
    QuestionBlueprint(
        topic="Compound sentences",
        question="The weather was cold, ___ we stayed inside.",
        correct_answer="so",
        distractors=("because", "although", "unless", "if"),
        rule="A compound sentence joins two independent clauses with a coordinating conjunction.",
        explanation="So joins two independent clauses and shows the result of the cold weather.",
        sentence_explanation="The weather was cold, so we stayed inside.",
    ),
    QuestionBlueprint(
        topic="Complex sentences",
        question="We left early ___ the road was closing.",
        correct_answer="because",
        distractors=("and", "but", "or", "yet"),
        rule="A complex sentence uses a dependent clause to explain or modify the main clause.",
        explanation="Because introduces the dependent clause that explains why we left early.",
        sentence_explanation="We left early because the road was closing.",
    ),
    QuestionBlueprint(
        topic="Adjective clauses",
        question="The teacher ___ helped me was very kind.",
        correct_answer="who",
        distractors=("where", "when", "what", "whose"),
        rule="An adjective clause describes a noun and often begins with a relative pronoun.",
        explanation="Who introduces the clause that describes the teacher.",
        sentence_explanation="The teacher who helped me was very kind.",
    ),
    QuestionBlueprint(
        topic="Adverb clauses",
        question="We waited inside ___ the rain stopped.",
        correct_answer="until",
        distractors=("who", "that", "despite", "although"),
        rule="An adverb clause can show time, condition, reason, or contrast.",
        explanation="Until introduces a time clause showing when we waited inside.",
        sentence_explanation="We waited inside until the rain stopped.",
    ),
    QuestionBlueprint(
        topic="Noun clauses",
        question="I don't know ___ she meant.",
        correct_answer="what",
        distractors=("where", "when", "whose", "how much"),
        rule="A noun clause can act as the object of a verb like know.",
        explanation="What she meant is the noun clause that works as the object of know.",
        sentence_explanation="I don't know what she meant.",
    ),
    QuestionBlueprint(
        topic="Present participles",
        question="I saw the children ___ in the park.",
        correct_answer="playing",
        distractors=("played", "play", "to play", "plays"),
        rule="A present participle can describe an action in progress.",
        explanation="Playing shows the children were in the middle of the action.",
        sentence_explanation="I saw the children playing in the park.",
    ),
    QuestionBlueprint(
        topic="Past participles",
        question="The letter was ___ yesterday.",
        correct_answer="sent",
        distractors=("sending", "send", "sends", "sender"),
        rule="Past participles often appear with forms of be in passive voice.",
        explanation="Sent is the past participle needed after was.",
        sentence_explanation="The letter was sent yesterday.",
    ),
    QuestionBlueprint(
        topic="Gerunds",
        question="___ regularly helps improve stamina.",
        correct_answer="Running",
        distractors=("Run", "To run", "Ran", "Runs"),
        rule="A gerund is a verb form ending in -ing that functions as a noun.",
        explanation="Running works as the subject of the sentence.",
        sentence_explanation="Running regularly helps improve stamina.",
    ),
    QuestionBlueprint(
        topic="Infinitives",
        question="He hopes ___ the exam.",
        correct_answer="to pass",
        distractors=("passing", "passed", "pass", "passes"),
        rule="An infinitive is to plus the base form of the verb.",
        explanation="To pass is the infinitive that follows hopes.",
        sentence_explanation="He hopes to pass the exam.",
    ),
    QuestionBlueprint(
        topic="Adjectives",
        question="She wore a ___ jacket.",
        correct_answer="red",
        distractors=("redden", "redness", "redly", "redder"),
        rule="Adjectives modify nouns.",
        explanation="Red is the adjective that describes jacket.",
        sentence_explanation="She wore a red jacket.",
    ),
    QuestionBlueprint(
        topic="Adverbs",
        question="He finished the work ___.",
        correct_answer="quickly",
        distractors=("quick", "quicker", "quickest", "quickness"),
        rule="Adverbs modify verbs, adjectives, or other adverbs.",
        explanation="Quickly tells us how he finished the work.",
        sentence_explanation="He finished the work quickly.",
    ),
    QuestionBlueprint(
        topic="Degrees of comparison",
        question="This puzzle is ___ than the last one.",
        correct_answer="harder",
        distractors=("hard", "hardest", "hardly", "more hard"),
        rule="Use the comparative form when comparing two things.",
        explanation="Harder is the comparative form used to compare two puzzles.",
        sentence_explanation="This puzzle is harder than the last one.",
    ),
    QuestionBlueprint(
        topic="Elliptical constructions",
        question="I can swim faster than he can ___.",
        correct_answer="swim",
        distractors=("swims", "swimming", "to swim", "swam"),
        rule="Elliptical constructions omit repeated words that are understood from context.",
        explanation="Swim is understood after can, so the sentence avoids repeating the verb phrase.",
        sentence_explanation="I can swim faster than he can swim.",
    ),
    QuestionBlueprint(
        topic="Parallel structure",
        question="The plan was to write, to edit, and ___.",
        correct_answer="to publish",
        distractors=("publishing", "published", "publish", "publishes"),
        rule="Items in a series should share the same grammatical form.",
        explanation="To publish matches the other infinitive phrases in the series.",
        sentence_explanation="The plan was to write, to edit, and to publish.",
    ),
    QuestionBlueprint(
        topic="Causative constructions",
        question="She had her laptop ___ yesterday.",
        correct_answer="repaired",
        distractors=("repair", "repairing", "repairs", "to repair"),
        rule="Causative structures can show that someone arranged for an action to happen.",
        explanation="Repaired shows she arranged for someone else to fix the laptop.",
        sentence_explanation="She had her laptop repaired yesterday.",
    ),
    QuestionBlueprint(
        topic="Conditional clauses",
        question="If I ___ enough time, I would travel more.",
        correct_answer="had",
        distractors=("have", "will have", "having", "has"),
        rule="Use the past form in a hypothetical conditional if-clause.",
        explanation="Had is correct because the sentence describes an unreal present situation.",
        sentence_explanation="If I had enough time, I would travel more.",
    ),
    QuestionBlueprint(
        topic="Subjunctive mood",
        question="The manager requested that he ___ early.",
        correct_answer="arrive",
        distractors=("arrives", "arrived", "arriving", "has arrived"),
        rule="In the subjunctive mood, base form verbs often follow demand or request verbs.",
        explanation="Arrive is the base form used after requested that.",
        sentence_explanation="The manager requested that he arrive early.",
    ),
    QuestionBlueprint(
        topic="Inverted subject and predicate",
        question="Under the bridge ___ a small boat.",
        correct_answer="was",
        distractors=("were", "are", "be", "been"),
        rule="Inversion can place the verb before the subject for emphasis or style.",
        explanation="Was agrees with the singular subject a small boat after the prepositional phrase.",
        sentence_explanation="Under the bridge was a small boat.",
    ),
    QuestionBlueprint(
        topic="English usage",
        question="She has a deep ___ for music.",
        correct_answer="appreciation",
        distractors=("appreciate", "appreciator", "appreciatively", "appreciable"),
        rule="Choose the word that fits the sentence meaning and part of speech.",
        explanation="Appreciation is the noun that fits after deep.",
        sentence_explanation="She has a deep appreciation for music.",
    ),
    QuestionBlueprint(
        topic="Prepositional idioms",
        question="He is interested ___ science.",
        correct_answer="in",
        distractors=("on", "at", "with", "for"),
        rule="Many English expressions require a fixed preposition.",
        explanation="Interested in is the standard idiomatic combination.",
        sentence_explanation="He is interested in science.",
    ),
]
