# Generated by Django 6.1 on 2026-08-30 02:09
from __future__ import annotations

import hashlib
import json
from django.db import migrations, models


def update_levels_and_seed(apps, schema_editor):
    QuestionBankQuestion = apps.get_model("practice", "QuestionBankQuestion")
    from practice.question_bank import QUESTION_BANK

    for blueprint in QUESTION_BANK:
        payload = {
            "topic": blueprint.topic.strip(),
            "question": blueprint.question.strip(),
            "correct_answer": blueprint.correct_answer.strip(),
            "distractors": [choice.strip() for choice in blueprint.distractors],
            "secondary_topics": [topic.strip() for topic in blueprint.secondary_topics],
            "level": blueprint.level.strip().lower(),
        }
        serialized = json.dumps(payload, sort_keys=True, ensure_ascii=False)
        content_hash = hashlib.sha256(serialized.encode("utf-8")).hexdigest()

        obj = QuestionBankQuestion.objects.filter(question=blueprint.question).first()
        if obj:
            obj.level = blueprint.level
            obj.content_hash = content_hash
            obj.topic = blueprint.topic
            obj.correct_answer = blueprint.correct_answer
            obj.distractors = list(blueprint.distractors)
            obj.rule = blueprint.rule
            obj.explanation = blueprint.explanation
            obj.sentence_explanation = blueprint.sentence_explanation
            obj.secondary_topics = list(blueprint.secondary_topics)
            obj.save()
        else:
            QuestionBankQuestion.objects.create(
                topic=blueprint.topic,
                question=blueprint.question,
                correct_answer=blueprint.correct_answer,
                distractors=list(blueprint.distractors),
                rule=blueprint.rule,
                explanation=blueprint.explanation,
                sentence_explanation=blueprint.sentence_explanation,
                secondary_topics=list(blueprint.secondary_topics),
                level=blueprint.level,
                source="seed",
                generation_metadata={},
                content_hash=content_hash,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_testsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankquestion',
            name='level',
            field=models.CharField(db_index=True, default='intermediate', max_length=32),
        ),
        migrations.AddField(
            model_name='testsession',
            name='level',
            field=models.CharField(db_index=True, default='all', max_length=32),
        ),
        migrations.RunPython(update_levels_and_seed, migrations.RunPython.noop),
    ]
