# Generated by Django 6.1 on 2026-08-30 02:39
from __future__ import annotations

import hashlib
import json
from django.db import migrations, models


def seed_paragraphs(apps, schema_editor):
    ParagraphBankQuestion = apps.get_model("practice", "ParagraphBankQuestion")
    from practice.question_bank import PARAGRAPH_BANK

    for blueprint in PARAGRAPH_BANK:
        blanks_payload = [
            {
                "blank_id": blank.blank_id,
                "topic": blank.topic,
                "correct_answer": blank.correct_answer,
                "distractors": list(blank.distractors),
                "rule": blank.rule,
                "explanation": blank.explanation,
                "secondary_topics": list(blank.secondary_topics),
            }
            for blank in blueprint.blanks
        ]
        payload = {
            "text_with_blanks": blueprint.text_with_blanks.strip(),
            "blanks": [
                {
                    "blank_id": b["blank_id"],
                    "topic": str(b.get("topic", "")).strip(),
                    "correct_answer": str(b.get("correct_answer", "")).strip(),
                    "distractors": [str(d).strip() for d in b.get("distractors", [])],
                }
                for b in blanks_payload
            ],
            "level": blueprint.level.strip().lower(),
        }
        serialized = json.dumps(payload, sort_keys=True, ensure_ascii=False)
        content_hash = hashlib.sha256(serialized.encode("utf-8")).hexdigest()

        ParagraphBankQuestion.objects.get_or_create(
            content_hash=content_hash,
            defaults={
                "title": blueprint.title,
                "text_with_blanks": blueprint.text_with_blanks,
                "blanks": blanks_payload,
                "level": blueprint.level,
                "full_text": blueprint.full_text,
                "paragraph_explanation": blueprint.paragraph_explanation,
                "source": "seed",
                "generation_metadata": {},
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_questionbankquestion_level_testsession_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_with_blanks', models.TextField()),
                ('blanks', models.JSONField(default=list)),
                ('level', models.CharField(db_index=True, default='intermediate', max_length=32)),
                ('full_text', models.TextField()),
                ('paragraph_explanation', models.TextField()),
                ('source', models.CharField(default='seed', max_length=32)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='testsession',
            name='test_type',
            field=models.CharField(db_index=True, default='sentence', max_length=32),
        ),
        migrations.RunPython(seed_paragraphs, migrations.RunPython.noop),
    ]
