# Generated by Django 5.2.17 on 2026-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_paragraphbankquestion_testsession_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingPromptBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(default='opinion', max_length=64)),
                ('prompt', models.TextField()),
                ('level', models.CharField(db_index=True, default='intermediate', max_length=32)),
                ('min_words', models.PositiveIntegerField(default=250)),
                ('suggested_minutes', models.PositiveIntegerField(default=40)),
                ('guidance', models.JSONField(blank=True, default=list)),
                ('useful_vocabulary', models.JSONField(blank=True, default=list)),
                ('model_outline', models.TextField(blank=True)),
                ('source', models.CharField(default='seed', max_length=32)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
